# Generated by Django 4.1.4 on 2022-12-15 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='people',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=250)),
                ('P_img', models.ImageField(upload_to='pics')),
                ('p_desc', models.TextField()),
            ],
        ),
    ]
