# Generated by Django 4.1.4 on 2022-12-15 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_people'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='P_img',
            new_name='p_img',
        ),
    ]
